RicterZ/nhentai

nhentai/downloader.py
Pad the filenames with a width of 3 characters so that image viewers display files in the expected order.
=> Padding filenames with width 3

nhentai/cmdline.py, nhentai/command.py, nhentai/constant.py, nhentai/parser.py
Added new options and now is possible multiple arguments in -tag --artist, --character, --parody, --group, separating by comma.
eg: --artist mdo-h,tamano kedama
Wondering if has a better approach for multiple arguments using optparse.OptionParser(?)
FeelsBad using if ',' in tag_name: tag_name.split(';')
=> new options added [--artist, --character, --parody, --group]

README.rst, nhentai/cmdline.py, nhentai/command.py, nhentai/parser.py, nhentai/serializer.py, nhentai/utils.py
Now when --html command is executed, generates a json file with the doujin metadata.
Added a module (serializer) for future implementations if any other format is needed to serialize data.
Added language option. I wonder why did I forget?
=> Added language option and metadata serializer

nhentai/cmdline.py, nhentai/command.py, nhentai/parser.py
I added "--page-range" option.
Its usage likes "1,4-10,12", which means "page 1, page 4 to 10 and page 12".
Now we can use page_range option for favorite doujinshis.
Maybe this option could also be used in the general search.
=> add page_range option for favorites

nhentai/cmdline.py, nhentai/command.py, nhentai/serializer.py, nhentai/utils.py, requirements.txt
ComicInfo.xml is a common format to embed metadata into CBZ files, originating from the ComicRack reader app.
It's basically a `ComicInfo.xml` with all the information written into the CBZ file.
=> write ComicInfo.xml for CBZ files

README.rst, nhentai/cmdline.py, nhentai/command.py, nhentai/constant.py, nhentai/parser.py
Removed all --tag commands
--language is now a setting
cleaned some code
changed search crawler to search API
To --search API work I had  to make a workaround because nhentai api doesnt decode html escape properly
Recommend pushing to main, since is pretty much broken tag options https://github.com/RicterZ/nhentai/issues/121
and now is possible searching by tag with --search
e.g.: --search="artist:henredear, tag:lolicon"
=> --search fix, removed --tag commands

README.rst, nhentai/cmdline.py, nhentai/command.py, nhentai/utils.py, requirements.txt
Add support for converting to PDF by including a generate_pdf method that utilizes `img2pdf` python module and the relating command line options and documentation. 
Relates to issue #120
=> Add PDF support

nhentai/cmdline.py
Or it will cause an AttributeError:
Traceback (most recent call last):                                                        
File "/home/yunze/.local/bin/nhentai", line 11, in <module>                             
load_entry_point('nhentai==0.3.9', 'console_scripts', 'nhentai')()                    
File "/home/yunze/.local/lib/python3.8/site-packages/nhentai-0.3.9-py3.8.egg/nhentai/com
mand.py", line 19, in main                                                                
options = cmd_parser()                                                                
File "/home/yunze/.local/lib/python3.8/site-packages/nhentai-0.3.9-py3.8.egg/nhentai/cmd
line.py", line 207, in cmd_parser                                                         
not args.tag and not args.favorites: …
=> remove args.tag since no tag option in parser

nhentai/utils.py
Removes invalid characters from filename if the OS is win32 based.
=> Fix invalid filenames on Windows

nhentai/downloader.py, nhentai/logger.py, nhentai/parser.py
logger.warn has been deprecated since Python 3.3, the preferred function is now logger.warning.
https://stackoverflow.com/questions/15539937/whats-the-difference-between-logging-warn-and-logging-warning-in-python
=> Switching 'logger.warn' to 'logger.warning'

.gitignore, nhentai/serializer.py
Don't know why you're taking so long to fix this simple issue, so I made a pull request.
Reference : https://stackoverflow.com/questions/27092833/unicodeencodeerror-charmap-codec-cant-encode-characters
```
Traceback (most recent call last):
File "c:\python39\lib\runpy.py", line 197, in _run_module_as_main
return _run_code(code, main_globals, None,
File "c:\python39\lib\runpy.py", line 87, in _run_code
exec(code, run_globals)
File "C:\Python39\Scripts\nhentai.exe\__main__.py", line 7, in <module>
File "c:\python39\lib\site-packages\nhentai\command.py", line 102, in main
generate_cbz(options.output_dir, doujinshi, options.rm_origin_dir)
File "c:\python39\lib\site-packages\nhentai\utils.py", line 177, in generate_cbz
serialize_comicxml(doujinshi_obj, doujinshi_dir)
File …
```
=> Fix UnicodeEncodeError

nhentai/utils.py
Personally found out there was an error when I re-downloaded manga as cbz file. Error occured when origin-dir not found while cbz files exist. Fix it by skipping remaining process of generate_cbz function if exists.
=> fix file not found error when cbz file exists.

nhentai/cmdline.py
I noticed the if checks stop the artist tag from being used. I added the nots to allow the artist search to continue to the legacy search function.
=> Changed parser option checks to allow artist search

nhentai/constant.py
Sorry, I meant to have this wrapped up within a week, but life got complicated.
If there's still interest, here's a PR to fix #299. I opted not to split the config and SQLite db, since that feels like a separate discussion that shouldn't be bundled here. Tested on my Linux machine, seems to work fine and shouldn't affect users who don't care about the spec. Should be simple to expand the same idea to other OSes if anyone wants to.
I'm open to suggestions/criticisms if you have any, and I should be able to respond quickly this time.
=> Adhere to XDG base dir spec on Linux

nhentai/viewer/main.js
Gallery title names replace '\_' in the folder name with ' ' (`generate_main_html()`). To match against these title names when searching, we must also replace '\_' with ' ' for each folder name we add to the list of titles to unhide.
=> Fix gallery search for folders with underscore

nhentai/command.py, nhentai/doujinshi.py, nhentai/downloader.py, nhentai/utils.py
- When using `--meta --cbz` with a duplicated `cbz` file will result in this error.
- This was caused by the [downloader being skipped](https://github.com/RicterZ/nhentai/blob/dec3f44542d601641f88cf6a642f6d653eaffba6/nhentai/downloader.py#L125-L128), but not [the rest of the process](https://github.com/RicterZ/nhentai/blob/dec3f44542d601641f88cf6a642f6d653eaffba6/nhentai/command.py#L88-L94).
```
File "\?\A:\nhentai.venv\Scripts\nhentai-script.py", line 33, in <module>
sys.exit(load_entry_point('nhentai==0.5.7', 'console_scripts', 'nhentai')())
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "A:\nhentai.venv\Lib\site-packages\nhentai-0.5.7-py3.12.egg\nhentai\command.py", line 94, in main
generate_metadata_file(options.output_dir, table, doujinshi)
File …
```
=> Bug fixes & improve duplicate checks

nhentai/__init__.py, nhentai/cmdline.py, nhentai/command.py, nhentai/doujinshi.py, nhentai/downloader.py, nhentai/utils.py, pyproject.toml
1. change option from `--regenerate-cbz` to `--regenerate`, to indicate program regenerate pdf or cbz file
2. by default, if a pdf or a cbz file exists, skip following download and generation process
3. furthermore, if a pdf file exists, but someone still want to generate a cbz file, he can use `--cbz --regenerate` (under now program logic)
=> improve #342

nhentai/command.py, nhentai/doujinshi.py
- user should just pass `--regenerate` option to get back origin dir.
```
(.venv) PS G:\Exports\nhentai> nhentai --id 405076 --download --format '%t [%i]' --threads=4 --cbz --pdf --meta --output="test-output" --no-html --rm-origin-dir
[21:29:26] banner: nHentai ver 0.5.9: あなたも変態。 いいね?
[21:29:26] main: Using mirror: https://nhentai.net
[21:29:26] main: Using viewer template "default"
[21:29:26] check_cookie: Login successfully! Your username: ****
[21:29:26] doujinshi_parser: Fetching doujinshi information of id 405076
[21:29:27] start_download: Doujinshi will be saved at "test-output\[Poriuretan] Angai Noriki na Ko A Surprisingly Cooperative Girl [English] [405076]"
[21:29:28] download: Starting to download https://i.nhentai.net/galleries/2234228/1.jpg ...
...
[21:29:33] download: …
```
=> Fix some regressions after #343

nhentai/command.py, nhentai/downloader.py, nhentai/utils.py, tests/test_download.py
This bug is a regression caused by https://github.com/RicterZ/nhentai/pull/351
- The threads (renamed from size) argument was ignored, thus code was running sequentially
- Changed to `asyncio.sleep`, since `time.sleep` is blocking.
- Cleaned up dead code from multiprocessing library
- Fix httpx requests not using headers/proxy
`nhentai --id 405076 --download --format '%t [%i]' --threads=4 --output="output-1" --delay 1`
=> asyncio: fix downloader being run sequentially + httpx: fix proxy and missing headers

nhentai/doujinshi.py, nhentai/parser.py, nhentai/utils.py
- The output in the generated metadata.json was not in the correct format and would print the whole span.
- The field was missing in the generated info.txt
=> fix favorite_counts output in metadata

nhentai/downloader.py, nhentai/utils.py, tests/test_download.py
Unlike the destructor of cpp. function __del__() only be triggered while python is in gc. So this PR close the zipfile hander manually in the end of download.
And make a test to ensure the operation of the compression function
=> Close zipfile hander manually and add a test
