RicterZ/nhentai

.travis.yml, nhentai/__init__.py, nhentai/cmdline.py, nhentai/command.py, nhentai/doujinshi.py, nhentai/downloader.py, nhentai/logger.py, nhentai/parser.py, nhentai/utils.py, requirements.txt
- Implemented a Python 2 and Python 3 compatible singleton for Download class
- Made code Python 3 compatible so that the setup can be done from any base python installation 
- Bumped up version because of dependency changes
=> Python3 compatablility and new Singleton implementation

README.md
=> Add install for Gentoo

nhentai/cmdline.py, nhentai/command.py, nhentai/doujinshi.py, nhentai/downloader.py, nhentai/parser.py
Nhentai is able to temporary ban a user for too much consecutive connections, making this CLI fail with a "Max retries" error. This pull request ensures that this does not get in the way of the software and retries several time to connect to the server before giving up.
I also added some misc language fixes
=> Max retries + misc. language fixes

requirements.txt
I got error when installing and find this requirement.txt missing newline
=> requirement.txt missing new line

.gitignore, README.md, nhentai/viewer/scripts.js
Now you can use arrow to switch pages in `index.html` viewer.
Update `MIT` license badge.
=> Add viewer arrow support, add README license badge.

nhentai/cmdline.py, nhentai/doujinshi.py, nhentai/parser.py
```bash
nhentai --show --id 255714
```
**BEFORE:**
**AFTER:**
_Attention: I'm request to pull into `dev`, cause your `master` does not contain my former PR commits._
=> fix show info

README.rst, nhentai/parser.py
Didn't test since I'm using 4G (at work), but I'm sure there is no issues
=> Fixed parser to work with new options, and updated readme

nhentai/cmdline.py, nhentai/command.py, nhentai/parser.py
Should improve performance and stop this issue https://github.com/RicterZ/nhentai/issues/85
Lazy to test on python 2, but should be fine I think
=> changed all map(lambda) to listcomp

README.rst
--gen-main exists as an option in cmdline.py but is not documented in README
=> Documenting --gen-main

nhentai/viewer/scripts.js, nhentai/viewer/styles.css
Found reading text difficult on a small display so made some edits to the viewer.
Changed image size in styles.css to fill the width and scroll vertically, and changed Up/Down/W/S keybinds to scroll the page, albeit rudimentally.
=> Suggested change to viewer

nhentai/parser.py
nhentai's recent site update broke the parser, this fixes it. Based off the work on [my fork here](https://github.com/jwfiredragon/nhentai/commit/8c4a4f02bc0d551b13fd5c9e7da5afe3381c47d3).
=> Fixing parser for nhentai site update

nhentai/viewer/main.css
ms-user-select should be -ms-user-select. #0d0d0d9 isn't a valid hex code - I assume it's supposed to be #0d0d0d?
=> Fixing typos

nhentai/cmdline.py, nhentai/parser.py
=> Fix fatal error and keep index of id which from file

nhentai/cmdline.py, nhentai/parser.py
=> Revert "Fix fatal error and keep index of id which from file"

nhentai/cmdline.py, nhentai/command.py
Added **_--clean-language_** option to be able to delete the language settings entered by the user on the **_--language=DEFAULT_** option.
=> Added --clean-language option

nhentai/__init__.py, nhentai/doujinshi.py
Added the _**Parodies**_ info output.
Output from **nhentai --id 331317 --show** or **nhentai --id 331317 -S** : 
```
[12:37:18] [INFO] Print doujinshi information of 331317
----------  ------------------------------------------------------------------------------
Parodies    kanojo okarishimasu | rent-a-girlfriend
Doujinshi   [AMP (Norakuro Nero)] Kanojo, Otoshimasu (Kanojo, Okarishimasu)
Subtitle    [AMP (野良黒ネロ)] 彼女、堕とします (彼女、お借りします)
Characters  sumi sakurasawa
Authors     norakuro nero
Languages   japanese
Tags        sole female, stockings, sole male, schoolgirl uniform, dilf, bbm, mind control
URL         https://nhentai.net/g/331317
Pages       22
----------  ------------------------------------------------------------------------------
```
Also updated the **__version__** of the …
=> Added 'Parodies' output and Updated package version

nhentai/cmdline.py, nhentai/command.py, nhentai/parser.py
`nhentai --search "darling in the franxx" --page-all`  
Output example:
```
[18:44:03] [INFO] Search Result || Found 108 doujinshis 
======  =======================================================================================
id  doujinshi
======  =======================================================================================
328231  (C94) [Workaholic (Kni)] Robo Sukebe Bon | Robo Hentai Book [English] [Fated Circle]
318600  [Carrot Academy (carrot)] 満心総意の躾 (DARLING in the FRANXX)
313683  (C94) [Workaholic (Kni)] robo-hentai-book
308637  (GOOD COMIC CITY 25) [Bad Mushrooms (4why&Chicke III, mimo)] DARLING Ningen Shikkaku ..
300967  DArling Baby Maker
294623  zero tsu doujin
[summary (lots of doujinshis)]
228567  [Kouchaya (Ootsuka Kotora)] GERBERA (DARLING in the FRANXX) …
```
=> Added --page-all option to download all search results

nhentai/cmdline.py
=> Fix running without parameters

MANIFEST.in, nhentai/command.py
=> Fix change directory output_dir option on gen-main

nhentai/utils.py
change to blacklist approach (allow 2-bytes character)
=> fix issue #186

nhentai/parser.py
=> Fixing loop when id not found, issue #188

nhentai/utils.py
`UnboundLocalError: local variable 'img2pdf' referenced before assignment`
=> FIX: Use of img2lib even if it is not installed

nhentai/command.py, nhentai/constant.py, nhentai/serializer.py, nhentai/utils.py
Since we are already generating a cbz, no reason to not just create the info.xml too. And I couldn't find any other option to allow the creation of the ComicInfo.xml file.
=> Changed write_comic_info from False to True

nhentai/cmdline.py, nhentai/command.py, nhentai/utils.py
Would be nice to have the option to just download meta data.
=> Add dryrun option to command line interface

nhentai/cmdline.py, nhentai/command.py, nhentai/doujinshi.py, nhentai/utils.py
This will add the --meta Parameter.
With which a info.txt File will be generated in HDoujin Format.
It´s mainly for Readers like Happypandax or Lanragi which can read that format.
=> HDoujin-format Metadata file

MANIFEST.in, nhentai/cmdline.py, nhentai/viewer/minimal/index.html, nhentai/viewer/minimal/scripts.js, nhentai/viewer/minimal/styles.css
A viewer for minimalistic needs:
- No sidebar
- Page number at bottom (not occupying doujinshi area)
- Fitting page to screen
Additionally, changed the behaviour ``nhentai --html`` to use config.json template
=> Add minimal viewer

README.rst
i submitted the package a while ago.
=> Nixos oneliner

README.rst, nhentai/cmdline.py, nhentai/command.py, nhentai/constant.py, nhentai/utils.py
need to pass cloudflare check once, then set user-agent and cookie
=> Add new option to avoid cloudflare captcha

nhentai/utils.py
Not entirety sure if I should of named it **GROUPS** or **GROUP**
=> Fixed info.txt

nhentai/command.py
=> --page-all works with favorites

README.rst, nhentai/cmdline.py, nhentai/command.py, nhentai/utils.py
=> Added --move-to-folder

nhentai/cmdline.py
sort api of nhentai.net changed recently. Fixed it in this commit.
=> fix nhentai.net api sort option changed from popular to popular-all

nhentai/doujinshi.py, nhentai/parser.py, nhentai/utils.py
=> add webp support

nhentai/downloader.py
And del func download_wrapper() to make class Download inheritable.
=> Use coroutine in url download

nhentai/downloader.py, requirements.txt
=> Fix issue #7

README.rst, nhentai/doujinshi.py, nhentai/parser.py, nhentai/serializer.py
Add functionality to add favorites count of the dounjinshi.
Uses %f to replace with metadata.
=> add favorites count metadata

nhentai/downloader.py, nhentai/utils.py, requirements.txt
Since there is only ever one proxy used, the logic could just be simplified.
=> HTTPX 0.28 support

README.rst
File `setup.py` was removed in commit d74fd103f0b834fe23ef9e0dd4ae395c28d51442; updated README to reflect the new installation process.
=> Update installation instructions in README.rst
